name: Kripto Fırsat Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # her 30 dakikada bir
  workflow_dispatch:        # elle başlatmak için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo’yu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: pip install -r requirements.txt || true

    - name: Botu çalıştır
      run: python kriptofırsat.py
