name: Kripto Fırsat Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir çalışır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          pip install requests python-telegram-bot

      - name: Botu çalıştır
        run: |
          python kriptofirsat.py
