name: Kripto Fırsat Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # her 5 dakikada bir çalıştırır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo’yu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        pip install python-telegram-bot requests

    - name: Botu çalıştır
      run: python3 kriptofırsat.py
